services:
  - type: web
    name: n8n-free-instance
    runtime: docker
    repo: https://github.com/mithilesh-id07/render-n8n
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 5678
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first
      - key: N8N_REINSTALL_MISSING_PACKAGES
        value: true
